CarDealership/Models/Manufacturer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarDealership.Models
{
    public class Manufacturer
    {
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(50)]
        public string State { get; set; }
        [StringLength(50)]
        public string City { get; set; }
        public ICollection<Car> Cars { get; set; }
        public ICollection<Contracts> Contracts { get; set; }


    }
}

CarDealership/Controllers/ManufacturerController.cs
using CarDealership.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarDealership.Controllers
{
    public class ManufacturerController : Controller
    {
        public DealershipDbContext db { get; set; } = new DealershipDbContext();
        // GET: Manufacturer
        public ActionResult Index()
        {
            var manufacturers = db.Manufacturers.ToList();

            return View(manufacturers);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Manufacturer manu)
        {
            try
            {
                db.Manufacturers.Add(manu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {

                return View();
            }
        }
    }
}

CarDealership/Views/Manufacturer/Create.cshtml
@model CarDealership.Models.Manufacturer
@{
    ViewBag.Title = "Create";
}

<h2>Add new manufacturer</h2>

@using (Html.BeginForm("Create", "Manufacturer", FormMethod.Post, new { id = "create_manu" }))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.City)
        @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.State)
        @Html.TextBoxFor(m => m.State, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <input class="btn btn-default" value="Add" type="submit" />
    </div>

}

CarDealership/Views/Manufacturer/Index.cshtml
@using CarDealership.Models
@model ICollection<Manufacturer>
@{
    ViewBag.Title = "Index";
}

<h2>List of car manufacturers</h2>

<table class="table table-bordered table-bordered table-hover">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>State</th>
        <th>City</th>
    </tr>
    @foreach (var m in Model)
    {
        <tr>
            <td>@m.Id</td>
            <td>@m.Name</td>
            <td>@m.State</td>
            <td>@m.City</td>
        </tr>
    }

</table>
