CarDealership/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarDealership.Models
{
    public class Car
    {
        public int Id { get; set; }
        [Required]
        public string Model { get; set; }
        public string Year { get; set; }
        public string Color { get; set; }
        [Required]
        public double? Volume { get; set; }
        public int? ManufacturerId { get; set; }
        public Manufacturer Manufacturer { get; set; }
        public int? DealershipId { get; set; }
        public Dealership Dealership { get; set; }

    }   
}

CarDealership/Controllers/CarController.cs
using CarDealership.Models;
using CarDealership.ViewModel;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarDealership.Controllers
{
    public class CarController : Controller
    {
        public DealershipDbContext db { get; set; } = new DealershipDbContext();
       
        // GET: Car
        public ActionResult Index()
        {
            CarViewModel cvm = new CarViewModel()
            {
                Car = null,
                Cars = db.Cars.Include(c => c.Manufacturer).ToList()
            };
            
            return View(cvm);
        }

       
        public ActionResult Create()
        {
            CarManufacturerViewModel cmvm = new CarManufacturerViewModel()
            {
                Car = null,
                Manufacturers = db.Manufacturers.ToList()
            };
          
            return View(cmvm);
        }
        [HttpPost]
        public ActionResult Create(Car car)
        {
            try
            {
                db.Cars.Add(car);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch 
            {
                CarManufacturerViewModel cmvm = new CarManufacturerViewModel()
                {
                    Car = car,
                    Manufacturers = db.Manufacturers.ToList()
                };

                return View(cmvm);

            }
          
        }
    }
}

CarDealership/Views/Car/Create.cshtml
@using CarDealership.ViewModel
@model CarManufacturerViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Add new car</h2>
<div>
    @using (Html.BeginForm("Create", "Car", FormMethod.Post, new { id = "create_car" }))
    {
        <div>
            @Html.LabelFor(m => m.Car.Model)
            @Html.TextBoxFor(m => m.Car.Model)
        </div>
        <div>
            @Html.LabelFor(m => m.Car.Color)
            @Html.TextBoxFor(m => m.Car.Color)
        </div>
        <div>
            @Html.LabelFor(m => m.Car.Year)
            @Html.TextBoxFor(m => m.Car.Year)
        </div>
        <div>
            @Html.LabelFor(m => m.Car.Volume)
            @Html.TextBoxFor(m => m.Car.Volume)
        </div>
        <div class="form-group">
            @Html.DropDownListFor(m => m.Car.ManufacturerId, new SelectList(Model.Manufacturers, "Id", "Name"), "Select manufacturer")

        </div>

        <div class="form-group">
            <input class="btn btn-default" type="submit" />
        </div>


    }
</div>


CarDealership/Views/Car/Index.cshtml
@using CarDealership.ViewModel
@model CarViewModel

<h2>List of cars</h2>
<div class="container">
    <table class="table table-bordered table-bordered table-hover">       
            <tr>
                <th>Model</th>
                <th>Manufacturer</th>
                <th>Year</th>
                <th>Color</th>
                <th>Volume</th>
            </tr>       
            @foreach (var m in Model.Cars)
            {
                <tr>
                    <td>@m.Model</td>
                    <td>@m.Manufacturer.Name</td>
                    <td>@m.Year</td>
                    <td>@m.Color</td>
                    <th>@m.Volume</th>
                </tr>
            }
    </table>

</div>
