CarDealership/Models/Dealership.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CarDealership.Models
{
    public class Dealership
    {
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(50)]
        public string State { get; set; }
        [StringLength(50)]
        public string City { get; set; }
        [Required]        
        [StringLength(50)]
        public string PIB { get; set; }
        [StringLength(50)]
        public string Address { get; set; }        
        public ICollection<Car> Cars { get; set; }
        public ICollection<Contracts>Contracts { get; set; }



    }
}

CarDealership/Controllers/DealershipController.cs
using CarDealership.Models;
using CarDealership.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarDealership.Controllers
{
    public class DealershipController : Controller
    {
        public DealershipDbContext db { get; set; } = new DealershipDbContext();
       
        public ActionResult Index()
        {
            var dealership = db.Dealerships.ToList();
            return View(dealership);
        }

        public ActionResult Create()
        {          
            return View();
        }

        [HttpPost]
        public ActionResult Create(Dealership deal )
        {
            try
            {              
                db.Dealerships.Add(deal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {                            
                return View(deal);
            }
        }

        public ActionResult Details(int id)
        {
            var dealership = db.Dealerships
                                .Where(d => d.Id == id)
                                .Include(d => d.Cars)
                                .Include(d=>d.Contracts.Select(c=>c.Manufacturer))
                                .FirstOrDefault();

            return View(dealership);

        }

        public ActionResult Contract(int id)
        {
            DealershipManufacturersViewModel dmvm = new DealershipManufacturersViewModel();
            dmvm.Manufacturers = db.Manufacturers.ToList();
            dmvm.DealershipId = id;
            return View(dmvm);
        }
        [HttpPost]
        public ActionResult Contract(DealershipManufacturersViewModel dmvm)
        {
            try
            {
                Contracts dm = new Contracts()
                {
                    DealershipId = dmvm.DealershipId,
                    ManufacturerId = dmvm.ManufacturerId
                };

                db.Contracts.Add(dm);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                dmvm.Manufacturers = db.Manufacturers.ToList();
                return View(dmvm);
            }
        }

        public ActionResult AddCar(int id)
        {
            var contract = db.Contracts // U veznoj tabeli pronadje sve ugovore koje prodavnica ima
                             .Where(c => c.DealershipId == id)
                             .Select(c => c.ManufacturerId)
                             .ToList();

            List<Car> cars = new List<Car>();

            foreach (var c in contract) // popunjava listu sa automobilima od onih proizvodjaca sa kojima prodavnica ima ugovor
            {                               //i ignorise one koji su vec dodati
                cars.AddRange(db.Cars
                          .Where(m => m.ManufacturerId == c && m.DealershipId !=id ).ToList());
            }

            DealershipCarsViewModel model = new DealershipCarsViewModel()
            {
                DealershipId = id,
                Cars = cars
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult AddCar(DealershipCarsViewModel model)
        {
            var car = db.Cars.Find(model.CarId);
            var dealership = db.Dealerships.Find(model.DealershipId);
            car.Dealership = dealership;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CarDealership/Views/Dealership/AddCar.cshtml
@using CarDealership.ViewModel
@model DealershipCarsViewModel
@{
    ViewBag.Title = "AddCar";
}

<h2>AddCar</h2>

@using (Html.BeginForm("AddCar", "Dealership", FormMethod.Post))
{
    @Html.HiddenFor(m => m.DealershipId)

    @Html.DropDownListFor(m => m.CarId, new SelectList(Model.Cars, "Id", "Model"), "Select car")
    <input type="submit" class="btn btn-default" value="Save contract">
}

CarDealership/Views/Dealership/Contract.cshtml
@using CarDealership.ViewModel
@model DealershipManufacturersViewModel
@{
    ViewBag.Title = "Contract";
}

<h2>Contract</h2>

@using (Html.BeginForm("Contract", "Dealership", FormMethod.Post))
{
@Html.HiddenFor(m=>m.DealershipId)

@Html.DropDownListFor(m => m.ManufacturerId, new SelectList(Model.Manufacturers, "Id", "Name"), "Select manufacturer")
<input type="submit" class="btn btn-default" value="Save contract">

}

CarDealership/Views/Dealership/Create.cshtml
@using CarDealership.Models
@model Dealership
@{

    ViewBag.Title = "Create";
}

<h2>Add dealership</h2>

@using (Html.BeginForm("Create","Dealership", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.PIB)
        @Html.TextBoxFor(m => m.PIB, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.State)
        @Html.TextBoxFor(m => m.State, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.City)
        @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
    </div>
     
    <div class="form-group">
        <input class="btn btn-default" value="Add" type="submit" />
    </div>
}

CarDealership/Views/Dealership/Details.cshtml
@using CarDealership.Models
@model Dealership
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<h2>Dealership: @Model.Name</h2>
<h4>City: @Model.PIB</h4>
<h4>State: @Model.State</h4>
<h4>PIB: @Model.City</h4>



<table class="table table-bordered table-striped table-hover">
    <tr>
        <th>Model</th>
        <th>Year</th>
        <th>Color</th>
        <th>Volume</th>
        <th>Manufacturer</th>
    </tr>
    @foreach (var car in Model.Cars)
    {
        <tr>
            <th>@car.Model</th>
            <th>@car.Year</th>
            <th>@car.Color</th>
            <th>@car.Volume</th>
            <th>@car.Manufacturer.Name</th>
        </tr>
    }
</table>
@Html.ActionLink("Add car", "AddCar", new { id = Model.Id })

<table class="table table-bordered table-striped table-hover">
    <tr>
        <th>Manufacturer</th>
        <th>State</th>
        <th>City</th>

    </tr>
    @foreach (var con in Model.Contracts)
    {
        <tr>
            <th>@con.Manufacturer.Name</th>
            <th>@con.Manufacturer.State</th>
            <th>@con.Manufacturer.City</th>

        </tr>
    }
</table>
@Html.ActionLink("New contract", "Contract", new { id = Model.Id })

CarDealership/Views/Dealership/Index.cshtml
@using CarDealership.Models
@model IEnumerable<Dealership>
@{
    ViewBag.Title = "Index";
}
@if (Model == null)
{
    <h2> No dealerships added </h2>
}
else
{
    foreach (var d in Model)
    {
    <h2 >Dealership: @d.Name</h2>
    <h4>City: @d.PIB</h4>
    <h4>State: @d.State</h4>
    <h4>PIB: @d.City</h4>
    @Html.ActionLink("Details","Details",new {id=d.Id})
    }

}